# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3dd4994b43e6c83e593b5431315ad821b330785bd759f79563f0f8f40a4d6ad48d2070260ec81379090c497cd1f9fc7faaedf6d7512d8d6cc106133ad8c91a13

test:
  secret_key_base: 3123f7d17a468f87dfe08a3b8e58e2e0f1891c68e898e56e52bf9053e4a8996b5f344c6bc3b6dfb665250c8c99c12cda9b83893220cc9446e226e80449dcc3c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
